### ISSUE TITLE
Enhancement: Drag/Drop Between Sheets

### ISSUE THREAD

**Issue by patrickburk1988** [Saibot393/droplet#1]
Hello! Love this idea for a module. Unfortunately, it doesn't appear to be working with the Unknown Armies system (installable using the following link, if you wanted to test it: https://raw.githubusercontent.com/patrickburk1988/unknownarmies/main/system.json). Specifically, transferring an item between sheets doesn't delete the item from the original sheet, regardless of whether the setting is enabled. Is there something specific I need to be doing to make this work?

Thanks!

**Comment by Saibot393** [comment]
Ok, i just did a bit of testing and it seems to work with all item types (artifact, item ritual, spell). Could you send me the .json export of a character with an item for which this does not work so that i could dig deeper into the problem?

**Comment by patrickburk1988** [comment]
Thanks for looking into it. Here's the JSON export: [fvtt-Actor-bob-JN1zi4jo2Yrsutjm.json](https://github.com/Saibot393/droplet/files/14426417/fvtt-Actor-bob-JN1zi4jo2Yrsutjm.json)

For what it's worth, it could be that I've misunderstood the purpose of the module. But here's a video showing the problem. As you can see, the `Delete item on transfer` setting is enabled. When dragging the item from Bob to Alice, though, the item remains on Bob's sheet: https://i.imgur.com/BKtb2Q8.mp4

**Comment by Saibot393** [comment]
Ah ok, i see the problem, drag and drop currently only works for tokens (so in the video you could drap bobs item onto alices token and it should behave as expected). I can add it for character sheets too though.

**Comment by patrickburk1988** [comment]
Ohh, gotcha. Yeah, if you're accepting feature requests, I think that would be a good one. Thanks again!

**Comment by Saibot393** [comment]
yes, i am open for all ideas/requests/suggestions, that should be a relatively easy one

**Comment by Saibot393** [comment]
I have added a setting to apply the drag & drop behaviour to sheet drops with v1.1.0 (activated by default)
