### ISSUE TITLE
Feature Request: Choose how many to transfer if item quantity is greater than 1

### ISSUE THREAD

**Issue by Rabulias** [Saibot393/droplet#2]
For example, Player A has 20 arrows and Player B has none.

Player A drags Arrows to Player B's token. Since Player A has 20 Arrows, a dialog prompt pops up for Player A asking "How many Arrows do you want to give to Player B?" with a number entry field.

There would be a "Transfer" button and a "Cancel Transfer" button, and maybe a "Transfer All" button for those times when Player A really does want to give Player B all his Arrows.

Thanks for making the module. I have been looking for something to replace Drag'N'Transfer.

**Comment by Saibot393** [comment]
Sure, sound like a usefull improvements (for ease of use i will probably also make it, so that shift automatically transfers all without opening the window)

**Comment by Saibot393** [comment]
I have added a setting to show a dialog to choose the transfer amount with v1.1.0 (the setting can be inverted by holding CTRL)
