### ISSUE TITLE
Feature Request: Hold ALT while dragging to override Delete After Transfer

### ISSUE THREAD

**Issue by Rabulias** [Saibot393/droplet#3]
Add the option to hold down the ALT key when transferring items to force it to not delete the item after transfer (temporarily reverting to the default Foundry VTT behavior of copying the item, not moving it).

The old Drag'n'Transfer module did this. Most of the time I wanted to move items, but every now and then as GM I would need to copy an item. The ALT key made this easy to do quickly when I needed to.

Thanks for considering this!

**Comment by Saibot393** [comment]
Should be easy enough to do, i will add it with the next version (i will probably make alt just invert the delete behaviour so that alt will delete items if the default behaviour is not deleting the item)

**Comment by Saibot393** [comment]
Added with v1.1.0
