### ISSUE TITLE
Bug: Error When Dropping onto Same Sheet

### ISSUE THREAD

**Issue by patrickburk1988** [Saibot393/droplet#4]
Hello! Found a bug, I think (or perhaps it's system specific?). When dragging-and-dropping items to reorder them within a sheet, it randomly seems to delete the reordered item. This additionally throws an `[ITEM] does not exist in the embedded collection` error, both as a modal popup and in the console. Everything seems to work fine once the `Apply settings to sheet drops` setting is disabled.

**Comment by Saibot393** [comment]
The bug should be fixed with v1.1.1
