### ISSUE TITLE
Bug: Containers leave behind duplicate items when moved

### ISSUE THREAD

**Issue by lholden** [Saibot393/droplet#5]
When dragging a container (like a backpack) containing items (like a ration or another container) to another character sheet, it leaves behind duplicates on the original character sheet. This is true for NPC sheets as well.

Reproduction Steps:
1. Create a new world
2. Enable just the Droplet module
3. Make two PC Actors, A and B
4. Put a backpack in Actor A's inventory
5. Put a ration in Actor A's inventory
6. Put a Pouch in Actor A's inventory
7. Drag Backback to Actor B
8. Notice that the Backpack on Actor B correctly has the two items it contained, but the ration and the pouch got left behind.

Console log of the above reproduction steps:
[console-export-2024-9-23_1-59-12.txt](https://github.com/user-attachments/files/17093178/console-export-2024-9-23_1-59-12.txt)

Additional console log from my actual world that also has droplet related errors in it (different from above):
[console-export-2024-9-23_2-0-53.txt](https://github.com/user-attachments/files/17093192/console-export-2024-9-23_2-0-53.txt)

![image](https://github.com/user-attachments/assets/3e50dad4-b0d0-40b2-9a32-7b02142f1d10)

**Comment by Saibot393** [comment]
The bug should now be solved with v2.0.1. While this is the case for the D&D5e system, there might be systems where this is not the case depending on how exactly containers are implemented (though it should work for most systms).

Also, thank you for the detailed description, quite helpfull.

**Comment by lholden** [comment]
> Also, thank you for the detailed description, quite helpfull.

I'm glad to help! :D
