### ISSUE TITLE
Bug: Dragging quantities of items has some bugs

### ISSUE THREAD

**Issue by lholden** [Saibot393/droplet#6]
When dragging quantities of items, I noticed several issues.

1. Closing the dialog acts like pressing "All" where I'd expect it to cancel the transfer
2. Holding alt while dragging (to duplicate) and then closing the Transfer dialog results in an error.
3. Selecting 0 leaves an item with zero quantity on the destination actor. (I assume this is intended?)
4.. The dialog says "Transfer" when moving a quantity, which was a little confusing. Perhaps it should say "Copy" or "Duplicate"?

![image](https://github.com/user-attachments/assets/65840d82-094b-4010-93d3-9249f47ef082)

### Reproduction of 1
1. Make a stack of 10 of Oil on Actor A
2. Drag the stack from Actor A to Actor B
3. Close the Transfer dialog
4. Notice that items are moved to Actor B

### Reproduction of 2
1. Make a stack of 10 of Oil on Actor A
2. Hold ALT and Drag the stack from Actor A to Actor B
3. Close the Transfer dialog
4. Notice the error generated in Console

### Reproduction of 3
1. Make a stack of 10 of Oil on Actor A
2. Drag the stack from Actor A to Actor B
3. In the Transfer dialog, drag slider to 0
4. In the Transfer dialog, click Accept
5. Notice that a the item is now on Actor B with a 0 quantity

**Comment by Saibot393** [comment]
The issue should be resolved with v2.1.0:

1. Closing the window will now transfer 0 items
2. The errror will no longer show up
3. I have added a setting called "Transfer zeros" to set the behaviour for these cases
4. The title of the transfer window will now be titled "Duplicate" in these cases

**Comment by lholden** [comment]
> The issue should be resolved with v2.1.0:

:heart: I appreciate the updates!

**Comment by Saibot393** [comment]
Glad to hear that, also, thanks again for the detailed description.
